//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HidalgoCastro.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Auth = new HashSet<Auth>();
            this.UserRole = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Gender { get; set; }
        public int SocialId { get; set; }
        public string Provider { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAT { get; set; }
    
        public virtual ICollection<Auth> Auth { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
